backend/controllers/SiteController.php
<?php

namespace backend\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use common\models\LoginForm;
use yii\filters\VerbFilter;
use common\models\Business;
use common\models\BusinessSearch;
use common\models\Franchise;
use common\models\FranchiseSearch;
use common\models\Cities;
use common\models\User;
use yii\web\UnauthorizedHttpException;
use common\models\CommunityComments;
use common\models\CommunityCommentsSearch;

/**
 * Site controller
 */
class SiteController extends \common\config\Controller3 {

  /**
   * @inheritdoc
   */
  public function behaviors() {
    return [
      'access' => [
        'class' => AccessControl::className(),
        'rules' => [
            [
            'actions' => ['login', 'error', 'requestpassword', 'requestpassword', 'rest_pass', 'rest_pass', 'reset-password', 'reset-password', 'check'],
            'allow' => true,
          ],
            [
            'actions' => ['logout', 'index'],
            'allow' => true,
            'roles' => ['@'],
          ],
        ],
      ],
      'verbs' => [
        'class' => VerbFilter::className(),
        'actions' => [
          'logout' => ['post'],
        ],
      ],
    ];
  }

  /**
   * @inheritdoc
   */
  public function actions() {
    return [
      'error' => [
        'class' => 'yii\web\ErrorAction',
      ],
    ];
  }

  public function actionCheck() {
    \chargebee\ChargeBee\Environment::configure("tls12", "JrnXj5Fi7xQbx2BWFdw6Vlbv3WINv9i0");
    try {
      $all = \chargebee\ChargeBee\Models\Subscription::all(array(
            "limit" => 1
      ));
    }
    catch (\chargebee\ChargeBee\Exceptions\APIError $e) {
      $jsonObj = $e->getJsonObject();
      if ($jsonObj['api_error_code'] == "api_authentication_failed") {
        echo "Connection to TLS1.2 works.\n";
      }
      else {
        echo "Please contact support@chargebee.com with the below msg:\n";
        print_r($jsonObj);
      }
    }
    catch (Exception $e) {
      echo "Contact your technical team / hosting provider for TLS1.2 support.\n";
      print_r($e->getMessage());
    }
  }

  public function actionIndex() {
    if (\Yii::$app->user->isGuest) {
      throw new UnauthorizedHttpException(Yii::t('app', 'Authorization Error!, you are not authorized to perform this action.'));
    }
    if (!\Yii::$app->user->isGuest) {
      $user = User::findByUsername(\Yii::$app->user->identity->username);
      if (!$user->isAdmin) {
        throw new UnauthorizedHttpException(Yii::t('app', 'Authorization Error!, you are not authorized to perform this action.'));
      }
    }

    return $this->render('index', [
    ]);
  }

  public function actionLogin() {
    if (!\Yii::$app->user->isGuest) {
      $user = User::findByUsername(\Yii::$app->user->identity->username);
      if (!$user->isAdmin) {
        throw new UnauthorizedHttpException(Yii::t('app', 'Authorization Error!, you are not authorized to perform this action.'));
      }
      return $this->goHome();
    }


    $model = new LoginForm();
    if ($model->load(Yii::$app->request->post()) && $model->login()) {

      $user = User::findByUsername(\Yii::$app->user->identity->username);
      if (!$user->isAdmin) {
        throw new UnauthorizedHttpException(Yii::t('app', 'Authorization Error!, you are not authorized to perform this action.'));
      }
      return $this->goBack();
    }
    else {
      return $this->render('login', [
            'model' => $model,
      ]);
    }
  }

  public function actionRequestpassword() {

    return $this->render('reset_password_form');
  }

  public function actionRest_pass() {

    $email = Yii::$app->request->post('email');
    if ($email == null || $email == '') {
      \Yii::$app->getSession()->setFlash('s_error', 'Email Required. ');
      return $this->redirect(Yii::$app->request->referrer);
    }

    $user = User::findOne(['email' => $email, 'is_admin' => 1]);
    if ($user != null) {
      $to = $email;
      $subject = "Password reset for Admin ";
      $token = $user['id'];

      $message = "
				<html>
				<head>
				<title>Password Reset</title>
				</head>
				<body>
				<p>Dear " . $user['username'] . ",
				<br>
				Click on below link to reset password. 
				</p>
				<p><a href=" . Yii::$app->urlManager->createAbsoluteUrl(['/site/reset-password', 'token' => base64_encode($token)]) . ">Reset Password</a></p>
				
				</body> 
				</html> 
				";

      // Always set content-type when sending HTML email
      $headers = "MIME-Version: 1.0" . "\r\n";
      $headers .= "Content-type:text/html;charset=UTF-8" . "\r\n";

      // More headers
      $headers .= 'From: ' . Yii::$app->params['name'] . "\r\n";

      mail($to, $subject, $message, $headers);

      \Yii::$app->getSession()->setFlash('s_mesage', 'Request for password submitted successfuly.Please check your email. ');
      return $this->redirect(Yii::$app->request->referrer);
    }
    else {
      \Yii::$app->getSession()->setFlash('s_error', 'Sorry, we are unable to reset password for email provided. ');
      return $this->redirect(Yii::$app->request->referrer);
    }
    return $this->redirect(Yii::$app->request->referrer);
  }

  public function actionResetPassword($token) {
    /*  try {
      $model = new \frontend\models\ResetPasswordForm($token);
      } catch (InvalidParamException $e) {
      throw new BadRequestHttpException($e->getMessage());

      } */

    $id = base64_decode($token);
    $user = User::findOne(['id' => $id, 'is_admin' => 1]);
    if ($user != null) {
      if (Yii::$app->request->post()) {

        $password = Yii::$app->request->post('password');
        $newPass = Yii::$app->security->generatePasswordHash($password);
        $model1 = User::findOne(['id' => $id]);
        $model1->password_hash = $newPass;
        $model1->save();

        \Yii::$app->getSession()->setFlash('s_mesage', 'Password Changed Successfully. ');

        return $this->goHome();
      }

      return $this->render('resetPassword');
    }
  }

  public function actionLogout() {
    Yii::$app->user->logout();

    return $this->goHome();
  }

}

frontend/controllers/SiteController.php
<?php

namespace frontend\controllers;

use Yii;
use common\models\LoginForm;
use \common\config\Options;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use frontend\models\ContactForm;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\web\UploadedFile;
use common\models\Faq;
use common\models\Newsletteremails;
use common\models\Needhelp;
use common\models\NeedhelpSearch;
use common\models\Settings;
use yii\data\Pagination;
use common\config\Controller2;
use common\models\User;
use yii\web\Response;
use yii\widgets\ActiveForm;

/**
 * Site controller
 */
class SiteController extends Controller2 {

    public $loginSuccessfull = "Login successful, welcome to Portal";
    public $signupSuccessfull = "Thank you for Signing Up with Portal";
    public $logoutsuccess = "You have successfully logout of Portal";

    /**
     * @inheritdoc
     */
    public function behaviors() {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
// 'logout' => ['post'],
                ],
            ],
        ];
    }

    public function actionFileupload($id) {
        $c_id = Yii::$app->getRequest()->getQueryParam('c_type');

        $dirpath = realpath(dirname(getcwd()));
        $uploaddir = $dirpath . '/web/uploads';
        foreach ($_FILES["image_path"]["error"] as $key => $error) {
            if ($error == UPLOAD_ERR_OK) {
                $tmp_name = $_FILES["image_path"]["tmp_name"][$key];
                $name = uniqid() . $_FILES["image_path"]["name"][$key];
                $name_db[] = $name;
                move_uploaded_file($tmp_name, "$uploaddir/$name");
            }
        }

        $connection = \Yii::$app->db;
        foreach ($name_db as $rs) {
            $file_name = 'uploads/' . $rs;
            $connection->createCommand()
                    ->insert('es_gallery', [
                        'image_path' => $file_name,
                        'option_id' => $id,
                        'option_type' => $c_id,
                    ])->execute();
        }
    }

    /**
     * @inheritdoc
     */
    public function actions() {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
            'auth' => [
                'class' => 'yii\authclient\AuthAction',
                'successCallback' => [$this, 'oAuthSuccess'],
            ],
        ];
    }

    /**
     * This function will be triggered when user is successfuly authenticated using some oAuth client.
     *
     * @param yii\authclient\ClientInterface $client
     * @return boolean|yii\web\Response
     */
    public function createAccount($userName, $email, $fName, $pic) {

        $user = new User();
        $user->username = $userName;
        $user->email = $email;
        $pass = rand(10, 1000000);
        $user->setPassword($pass);
        $user->f_name = $fName;
        $user->l_name = '';
        $user->address = '';
        $user->city = '';
        $user->country = '';
        $user->mobile = '-';
        $user->pic = $pic;
        $user->generateAuthKey();
        if ($user->save()) {
            $this->login($user);
        } else {
            \Yii::$app->getSession()->setFlash('s_mesage', Yii::t('app', 'Error while creating account'));
        }
    }

    private function login($user) {

        if (Yii::$app->user->login($user, 0)) {
            \Yii::$app->getSession()->setFlash('s_mesage', Yii::t('app', $this->loginSuccessfull));
        } else {
            \Yii::$app->getSession()->setFlash('s_mesage', Yii::t('app', 'Error while signin process'));
        }
    }

    public function oAuthSuccess($client) {


// get user data from client
        $userModel = new \common\models\User();
        $userAttributes = $client->getUserAttributes();
        $isNewUser = false;

        if (isset($userAttributes['name'])) {
            if (isset($userAttributes['email']) && isset($userAttributes['name'])) {

                $checkuser = \common\models\User::find()->where(['username' => $userAttributes['email']])->one();
                if ($checkuser != null) {
                    $this->login($checkuser);
                } else {
                    $checkuser1s = \common\models\User::find()->where(['email' => $userAttributes['email']])->one();
                    if ($checkuser1s != null) {
                        $this->login($checkuser1s);
                    } else {
                        $user = $this->createAccount($userAttributes['email'], $userAttributes['email'], $userAttributes['name'], '');
                        $isNewUser = true;
                    }
                }
            } else {
                $checkuser = \common\models\User::find()->where(['username' => $userAttributes['emails'][0]['value']])->one();
                if ($checkuser != null) {
                    $this->login($checkuser);
                } else {

                    $checkuser2s = \common\models\User::find()->where(['email' => $userAttributes['emails'][0]['value']])->one();
                    if ($checkuser2s != null) {
                        $this->login($checkuser2s);
                    } else {
                        $user = $this->createAccount($userAttributes['emails'][0]['value'], $userAttributes['emails'][0]['value'], $userAttributes['displayName'], $userAttributes['cover']['coverPhoto']['url']);
                        $isNewUser = true;
                    }
                }
            }
        }
        if (\Yii::$app->user->isGuest)
            return Yii::$app->getResponse()->redirect(Yii::$app->urlManager->createUrl("site/index"));
        else {
            if ($isNewUser == false)
                return Yii::$app->getResponse()->redirect(Yii::$app->urlManager->createUrl("site/dashboard"));
            else
                return Yii::$app->getResponse()->redirect(Yii::$app->urlManager->createUrl("user/viewown"));
        }
// do some thing with user data. for example with $userAttributes['email']
    }

    public function actionCp() {
        $setting = Settings::findOne(1);
        \chargebee\ChargeBee\Environment::configure($setting->cb_name, $setting->cb_api);

        $return_url = \yii\helpers\Url::to(['site/index']);
        $result = \chargebee\ChargeBee\Models\PortalSession::create(array("redirectUrl" => $return_url,
                    "customer" => array("id" => 'Hr551BIQX9frnY5YxB')));
        $account_url = $result->portalSession()->accessUrl;
        $this->redirect($account_url);
    }

    public function actionIndex() {

        $model = new \frontend\models\Boxchoice();
        if ($model->load(Yii::$app->request->post())) {
            $this->redirect(["join/index/", 'id' => $model->name]);
        }
        $newsmodel = new Newsletteremails();
        $model->name = 'monthly';
        return $this->render('index', ['model' => $model, 'newsmodel' => $newsmodel]);
    }

    public function actionGift() {
        return $this->render('gift');
    }

    public function actionFaq() {
        $this->mainMenu = 700;
        $faqModel = Faq::find()->orderBy('id')->all();
        return $this->render('faq', [
                    'faq' => $faqModel,
        ]);
    }

    public function actionCheck_user() {
        if (Yii::$app->user->isGuest) {
            echo '1';
        } else {
            echo '2';
        }
    }

    public function actionFaqdetail($id) {
        $faqM = Faq::findOne(['id' => $id]);

        return $this->render('faq_detail', ['f_detail' => $faqM,]);
    }

    public function actionLogin() {
        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        $session = Yii::$app->session;
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            if ($session->get('subscribe') == null) {
                return $this->redirect(Yii::$app->request->referrer);
            } else {
                $plan = $session->get('plan');
                $coupon = $session->get('coupon');
                $utm_campaign = $session->get('utm_campaign');
                $utm_source = $session->get('utm_source');
                $utm_medium = $session->get('utm_medium');
                $utm_content = $session->get('utm_content');
                $session->remove('subscribe');
                $session->remove('plan');
                $session->remove('coupon');
                $session->remove('addon');
                $session->remove('utm_campaign');
                $session->remove('utm_source');
                $session->remove('utm_medium');
                $session->remove('utm_content');

                return Yii::$app->getResponse()->redirect(Yii::$app->urlManager->createUrl(["join/index", 'id' => $plan,
                                    'coupon' => $coupon, 'utm_campaign' => $utm_campaign, 'utm_source' => $utm_source,
                                    'utm_medium' => $utm_medium, 'utm_content' => $utm_content]));
            }
        } else {
            return $this->render('login', [
                        'model' => $model,
            ]);
        }
    }

    public function actionCheck_login() {
        $model = new LoginForm();
        $data = Yii::$app->request->post();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            \Yii::$app->getSession()->setFlash('s_mesage', Yii::t('app', $this->loginSuccessfull));
            $data = '1';
        } else {
            $data = '2';
        }
        echo $data;
    }

    public function actionLoginpopup() {

backend/views/site/_msgform.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\Messages */
/* @var $form yii\widgets\ActiveForm */
if (isset($reply)){
    $label = Yii::t('app', 'Reply Back');
    $blable = Yii::t('app', 'Reply');
}
else {
    $label = $model->getAttributeLabel('message');
    $blable = Yii::t('app', 'Send');
}
?>

<div class="messages-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'from_user')->hiddenInput()->label(false) ?>
    <?= $form->field($model, 'to_user')->hiddenInput()->label(false) ?>
    <?= $form->field($model, 'message')->textarea()->label($label) ?>
    <?= $form->field($model, 'parent_id')->hiddenInput()->label(false) ?>
    <?= $form->field($model, 'option_type')->hiddenInput()->label(false) ?>
    <?= $form->field($model, 'option_id')->hiddenInput()->label(false) ?>

    <div class="form-group">
        <?= Html::submitButton($blable, ['class' =>  'btn-u btn-u-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/site/error.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

$this->title = $name;
?>
<div class="site-error">

    

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

backend/views/site/index.php
<?php
/* @var $this yii\web\View */

use yii\helpers\Html;
use yii\grid\GridView;
use yii\bootstrap\Modal;

$this->title = \Yii::t('app', \Yii::$app->params['name']);
?>
<div class="site-index">
</div>

backend/views/site/login.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */

$this->title = 'Login';
//$this->params['breadcrumbs'][] = $this->title;
?>
<br>
<br>
<div class="site-login">
    

    <p>Please fill out the following fields to login:</p>
     <?php if (Yii::$app->session->getFlash('s_mesage')) { ?>
        <div class="alert alert-success">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            <?= Yii::$app->session->getFlash('s_mesage'); ?>
        </div>
        <?php
    }
    ?>
               <?php if (Yii::$app->session->getFlash('s_error')) { ?>
        <div class="alert alert-danger">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            <?= Yii::$app->session->getFlash('s_error'); ?>
        </div>
        <?php
    }
    ?>
    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'login-form']); ?>
                <?= $form->field($model, 'username') ?>
                <?= $form->field($model, 'password')->passwordInput() ?>
                <?= $form->field($model, 'rememberMe')->checkbox() ?>
            <div style="color:#999;margin:1em 0">
                    If you forgot your password you can <?= Html::a('reset it', ['site/requestpassword']) ?>.
                   
                </div>
                <div class="form-group">
                    <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
                </div>
            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

backend/views/site/requestPasswordResetToken.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \\common\models\PasswordResetRequestForm */

$this->title = 'Request password reset';
//$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-request-password-reset">
   <div class="row">
   <div class="col-md-3"></div>
   <div class="col-md-4 business_box" style="padding-left: 5%">
    <h1 style="font-size:20px;"><?= Html::encode($this->title) ?></h1>
<?php if (Yii::$app->session->getFlash('s_mesage')) { ?>
        <div class="alert alert-success">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            <?= Yii::$app->session->getFlash('s_mesage'); ?>
        </div>
    <?php } ?>
    <p>Please fill out your email. A link to reset password will be sent in email.</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'request-password-reset-form']); ?>
                <?= $form->field($model, 'email') ?>
                <div class="form-group">
                    <?= Html::submitButton('Submit', ['class' => 'btn btn-primary']) ?>
                </div>
            <?php ActiveForm::end(); ?>
        </div>
    </div>
    </div>
    <div class="col-md-5"></div>
    </div>
</div>
<style>
#passwordresetrequestform-email { width: 155%; border-radius: 0px}
.help-block-error { width:142%;}
</style>

backend/views/site/resetPassword.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \\common\models\ResetPasswordForm */
//
//$this->title = 'Reset password';
//$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-reset-password">
    <h1 style=" margin-top:8%;"><?php //Html::encode($this->title) ?></h1>

    <p>Please choose your new password:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'reset-password-form']); ?>
                <?php //$form->field($model, 'password')->passwordInput() ?>
                <?=Html::input('password','password','',['class'=>'form-control'])?>
                <br />
                <div class="form-group">
                    <?= Html::submitButton('Save', ['class' => 'btn btn-primary']) ?>
                </div>
            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

backend/views/site/reset_password_form.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\helpers\BaseHtml;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */

$this->title = 'Password Reset';
//$this->params['breadcrumbs'][] = $this->title;
?>
<br>
<br>
<div class="site-login">
    

    <p>Please fill out the following fields :</p>
    <div class="row">
        <div class="col-lg-5">


    <div class="row">
        <div class="col-lg-8">
             <?php if (Yii::$app->session->getFlash('s_mesage')) { ?>
        <div class="alert alert-success">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            <?= Yii::$app->session->getFlash('s_mesage'); ?>
        </div>
        <?php
    }
    ?>
               <?php if (Yii::$app->session->getFlash('s_error')) { ?>
        <div class="alert alert-danger">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            <?= Yii::$app->session->getFlash('s_error'); ?>
        </div>
        <?php
    }
    ?>
            <?php $form = ActiveForm::begin(['action' => Yii::$app->urlManager->createUrl('/site/rest_pass')]); ?>
                
                   <?=Html::input('text','email','',['class'=>'form-control'])?>
            <br>
             <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
                </div>
                
                   
            
            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>