common/models/User.php
<?php

namespace common\models;

use Yii;
use yii\base\NotSupportedException;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;
use yii\web\IdentityInterface;

/**
 * User model
 *
 * @property integer $id
 * @property string $username
 * @property string $password_hash
 * @property string $password_reset_token
 * @property string $email
 * @property string $auth_key
 * @property integer $status
 * @property integer $created_at
 * @property integer $updated_at
 * @property string $password write-only password
 * @property string $f_name
 * @property string $l_name
 * @property string $is_admin
 * @property string $is_active
 * @property string $company_name
 * @property string $mobile
 * @property string $cb_customer_id
 * @property string $c_timestamp
 * @property string $tmp_pass
 */
class User extends ActiveRecord implements IdentityInterface {

  const STATUS_DELETED = 0;
  const STATUS_ACTIVE = 10;

  public $fullname = "";
  public $name = "";
  public $rate = "";
  private $isNew = false;

  public $password1 ='';
  public $password2 ='';
  /**
   * @inheritdoc
   */
  public static function tableName() {
    return 'es_user';
  }

  /**
   * @inheritdoc
   */
  public function behaviors() {
    return [
      TimestampBehavior::className(),
    ];
  }

  /**
   * @inheritdoc
   */
  public function rules() {
    return [
        ['status', 'default', 'value' => self::STATUS_ACTIVE],
        ['status', 'in', 'range' => [self::STATUS_ACTIVE, self::STATUS_DELETED]],
        [['company_name'], 'string', 'max' => 255],
        [['cb_customer_id'], 'string', 'max' => 100],
        [['mobile'], 'string', 'max' => 15],
        [['tmp_pass'], 'string', 'max' => 100],
        [['mobile', 'f_name', 'email'], 'required'],
    ];
  }

  public function attributeLabels() {
    return [
      'username' => Yii::t('app', 'User Name'),
      'f_name' => Yii::t('app', 'First Name'),
      'l_name' => Yii::t('app', 'Last Name'),
      'is_admin' => Yii::t('app', 'Admin'),
      'is_active' => Yii::t('app', 'Active'),
      'email' => Yii::t('app', 'Email'),
      'mobile' => Yii::t('app', 'Contact Number'),
      'notes' => Yii::t('app', 'Overview'),
      'company_name' => Yii::t('app', 'Company Name'),
      'c_timestamp' => Yii::t('app', 'Registration Date'),
      'creationdate' => Yii::t('app', 'Registration Date'),
      'cb_customer_id' => Yii::t('app', 'Chargebee Customer ID'),
      'tmp_pass' => 'Temporary Password',
      'password1' => 'Password',
      'password2' => 'Confirm Password',
    ];
  }

  public function getCreationdate() {
    return date('d/m/Y H:m', $this->created_at);
  }

  /**
   * @inheritdoc
   */
  public static function findIdentity($id) {
    return static::findOne(['id' => $id, 'status' => self::STATUS_ACTIVE]);
  }

  /**
   * @inheritdoc
   */
  public static function findIdentityByAccessToken($token, $type = null) {
    return static::findOne(['auth_key' => $token]);
  }

  /**
   * Finds user by username
   *
   * @param string $username
   * @return static|null
   */
  public static function findByUsername($username) {
    return static::findOne(['username' => $username, 'status' => self::STATUS_ACTIVE]);
  }

  /**
   * Finds user by password reset token
   *
   * @param string $token password reset token
   * @return static|null
   */
  public static function findByPasswordResetToken($token) {
    if (!static::isPasswordResetTokenValid($token)) {
      return null;
    }

    return static::findOne([
          'password_reset_token' => $token,
          'status' => self::STATUS_ACTIVE,
    ]);
  }

  /**
   * Finds out if password reset token is valid
   *
   * @param string $token password reset token
   * @return boolean
   */
  public static function isPasswordResetTokenValid($token) {
    if (empty($token)) {
      return false;
    }
    $expire = Yii::$app->params['user.passwordResetTokenExpire'];
    $parts = explode('_', $token);
    $timestamp = (int) end($parts);
    return $timestamp + $expire >= time();
  }

  /**
   * @inheritdoc
   */
  public function getIsAdmin() {
    return $this->is_admin;
  }

  public function getIsActive() {
    return $this->is_active;
  }

  public function getId() {
    return $this->getPrimaryKey();
  }

  /**
   * @inheritdoc
   */
  public function getAuthKey() {
    return $this->auth_key;
  }

  /**
   * @inheritdoc
   */
  public function validateAuthKey($authKey) {
    return $this->getAuthKey() === $authKey;
  }

  /**
   * Validates password
   *
   * @param string $password password to validate
   * @return boolean if password provided is valid for current user
   */
  public function validatePassword($password) {
    return Yii::$app->security->validatePassword($password, $this->password_hash);
  }

  /**
   * Generates password hash from password and sets it to the model
   *
   * @param string $password
   */
  public function setPassword($password) {
    $this->password_hash = Yii::$app->security->generatePasswordHash($password);
  }

  /**
   * Generates "remember me" authentication key
   */
  public function generateAuthKey() {
    $this->auth_key = Yii::$app->security->generateRandomString();
  }

  /**
   * Generates new password reset token
   */
  public function generatePasswordResetToken() {
    $this->password_reset_token = Yii::$app->security->generateRandomString() . '_' . time();
  }

  /**
   * Removes password reset token
   */
  public function removePasswordResetToken() {
    $this->password_reset_token = null;
  }

  public function afterFind() {
    $this->fullname = $this->f_name . ' ' . $this->l_name;
    $this->name = $this->f_name . ' ' . $this->l_name;
    parent::afterFind();
  }

  public function beforeSave($insert) {
    if ($this->isNewRecord) {
      $this->isNew = true;
    }
    return parent::beforeSave($insert);
  }

  public function afterSave($insert, $changedAttributes) {
    if ($this->isNew) {
//            $this->sendMail($this->email, $this->f_name);
    }
    return parent::afterSave($insert, $changedAttributes);
  }

  public function sendMail($to, $name) {
//    $rp = "NO MAIL";
//    $id = "signup";
//    $subject = "Congratulations on joining IService";
//    $emailtemplate = "";
//    $email = \common\models\Emailtemplate::findOne($id);
//    if ($email != null) {
//      if ($email->active == "1") {
//        $emailtemplate = $email->content;
//        $emailtemplate = str_replace('[USER_NAME]', $name, $emailtemplate);
//        $message = '<html><head><title>-</title></head><body>' . $emailtemplate . ' </body></html>';
//
//        $rp = @\Yii::$app->mailer->compose()
//                ->setFrom([\Yii::$app->params['adminEmail'] => 'IService'])
//                ->setTo($to)
//                ->setSubject($subject)
//                ->setHtmlBody($emailtemplate)
//                ->send();
//      }
//    }
    return;
  }

}

frontend/controllers/UserController.php
<?php

namespace frontend\controllers;

use yii\data\Pagination;
use Yii;
use common\models\User;
use common\models\UserSearch;
use common\config\Controller2;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;

Yii::setAlias('budyaga', '@vendor/budyaga');

/**
 * UnamesController implements the CRUD actions for Unames model.
 */
class UserController extends Controller2 {

    public $mainMenu = 500;
    public $submenu = 501;
    public $city = "";
    public $category = "";
    public $keyword = "";
    public $subcategory = "";
    public $dkeyword = "";
    public $pricesort = "";
    public $citysort = "";
    public $datesort = "";
    public $country = "";
    public $namesort = "";
    public $ratesort = "";

    public function behaviors() {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['updatelocation', 'update', 'viewown', 'updateimage', 'updatepimage', 'serviceprovider', 'addfavorite'],
                'rules' => [
                    [
                        'actions' => ['updatelocation', 'update', 'viewown', 'updateimage', 'updatepimage', 'serviceprovider', 'addfavorite'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                //  'delete' => ['post'],
                ],
            ],
        ];
    }

    public function actions() {

        return [
            'uploadPhoto' => [
                'class' => 'budyaga\cropper\actions\UploadAction',
                'url' => \common\config\Options::getFrontendAddress() . '/uploads',
                'path' => 'uploads',
            ]
        ];
    }

    public function actionAddfavorite($id) {

        $model = \common\models\Favoriteadd::findOne(['option_id' => $id, 'option_type' => Controller2::USERS, 'user_id' => Yii::$app->user->id]);
        if ($model == null) {
            $model = new \common\models\Favoriteadd();
            $model->option_id = $id;
            $model->option_type = Controller2::USERS;
            $model->user_id = Yii::$app->user->id;
            $model->save();
            \Yii::$app->getSession()->setFlash('s_mesage', Yii::t('app', 'Added to favourites'));
        } else {
            $model->delete();
            \Yii::$app->getSession()->setFlash('s_mesage', Yii::t('app', 'Removed from favourites'));
        }
        $this->redirect(array('user/view', 'id' => $id));
    }

    public function actionSearchprovider() {
        $city = Yii::$app->request->post('city') ? Yii::$app->request->post('city') : null;
        $country = Yii::$app->request->post('country') ? Yii::$app->request->post('country') : null;
        $keyword = Yii::$app->request->post('keyword') ? Yii::$app->request->post('keyword') : null;
        $category = Yii::$app->request->post('category') ? Yii::$app->request->post('category') : null;
        $subcategory = Yii::$app->request->post('sub_category') ? Yii::$app->request->post('sub_category') : null;

        return $this->redirect(['allsellers', 'city' => $city, 'category' => $category, 'keyword' => $keyword, 'subcategory' => $subcategory, 'country' => $country]);
    }

    public function actionAllsellers($country = null, $city = null, $category = null, $subcategory = null, $keyword = null, $dkeyword = null, $datesort = null, $pricesort = null, $ratesort = null, $namesort = null, $citysort = null, $operationType = 'search') {

        if (isset($_POST['button'])) {
            $operationType = $_POST['button'];
        }
        $city = Yii::$app->request->post('city') ? Yii::$app->request->post('city') : $city;
        $country = Yii::$app->request->post('country') ? Yii::$app->request->post('country') : $country;
        $keyword = Yii::$app->request->post('keyword') ? Yii::$app->request->post('keyword') : $keyword;
        $category = Yii::$app->request->post('category') ? Yii::$app->request->post('category') : $category;
        $subcategory = Yii::$app->request->post('sub_category') ? Yii::$app->request->post('sub_category') : $subcategory;

        $this->city = $city;
        $this->country = $country;
        $this->keyword = $keyword;
        $this->category = $category;
        $this->subcategory = $subcategory;
        $this->dkeyword = $dkeyword;
        $this->datesort = $datesort;
        $this->pricesort = $pricesort;
        $this->citysort = $citysort;
        $this->namesort = $namesort;
        $this->ratesort = $ratesort;


        $where = "status = '2'";
        if ($category != null) {
            $where.=" and category_id='" . $category . "'";
        }
        if ($subcategory != null) {
            $where.=" and sub_category_id='" . $subcategory . "'";
        }
        if ($country != null) {
            $where.=" and country='" . $country . "'";
        }
        if ($city != null) {
            $where.=" and city='" . $city . "'";
        }
        $where = "id in (select distinct user_id from es_business where " . $where . ")";

        if ($keyword != null) {
            $where.=" and (notes LIKE '%" . $keyword . "%' )";
        }

        $where.= "and account_type = '1'";
        $query = \common\models\User::find();
        $query = $query->where($where);

        $countQuery = clone $query;

        if ($citysort != null) {
            $query->orderBy('city ' . $citysort);
        }
        if ($namesort != null) {
            $query->orderBy('business_name ' . $namesort);
        }
        if ($ratesort != null) {
            $query->joinWith([ 'feedback']);
            $query->orderBy(' v_feedback_provider.rate ' . $ratesort);
        }
        if ($pricesort != null) {
            $query->joinWith([ 'feedback']);
            $query->orderBy(' v_feedback_provider.reviews ' . $pricesort);
        }

        $pages = new Pagination(['totalCount' => $countQuery->count()]);
        $models = $query->offset($pages->offset)
                ->limit($pages->limit)
                ->all();
        if ($models == null) {
            $cs_model = \common\models\Settings::findOne(['id' => 1]);
            \Yii::$app->getSession()->setFlash('danger', Yii::t('app', 'No Record Found. Try With Different One.'));
            $this->redirect(Yii::$app->request->referrer);
        } else {

            return $this->render('allsellers', [
                        'models' => $models,
                        'pages' => $pages,
            ]);
        }
    }

    public function actionServiceprovider($id) {
        $model = $this->findModel($id);
        if ($model->id != Yii::$app->user->id) {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
        $model->account_type = '1';
        if ($model->save()) {
            \Yii::$app->getSession()->setFlash('s_mesage', Yii::t('app', 'User have become service provider successfully.'));
        }
        return $this->redirect(['viewown']);
    }

    public function actionUpdatelocation($id) {
        $model = $this->findModel($id);

        if ($model->id != Yii::$app->user->id) {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
        $this->mainMenu = 150;
        $this->left_menu = 300;
        $this->submenu = 302;

        if ($model->load(Yii::$app->request->post())) {

            $model->lang = isset($uData['lang']) ? $uData['lang'] : "en";

            if ($model->save()) {
                return $this->redirect(['viewown', 'id' => $model->id]);
            }
        }
        return $this->render('updatlocation', ['model' => $model,]);
    }

    protected function uploadImage($model, $oldImage, $colname) {

        if (\yii\web\UploadedFile::getInstance($model, $colname)) {
            $fileObj = \yii\web\UploadedFile::getInstance($model, $colname);
            $filename = "";
            $dirpath = realpath(dirname(getcwd()));
            $filename = 'uploads/' . uniqid() . $colname . $fileObj->name;
            $fileObj->saveAs($dirpath . "/web/" . $filename);
            return $filename;
        } else {
            return $oldImage;
        }
    }

    /**
     * Updates an existing Unames model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id) {
        $model = $this->findModel($id);

        if ($model->id != Yii::$app->user->id) {
            throw new NotFoundHttpException('The requested page does not exist.');
        }

        $this->mainMenu = 150;
        $this->left_menu = 300;
        $this->submenu = 302;

        if ($model->load(Yii::$app->request->post())) {

            $uData = Yii::$app->request->post('User');
            $model->email = isset($uData['email']) ? $uData['email'] : "";
            $model->f_name = isset($uData['f_name']) ? $uData['f_name'] : "";
            $model->l_name = isset($uData['l_name']) ? $uData['l_name'] : "";
            $model->address = isset($uData['address']) ? $uData['address'] : "";
            $model->country = isset($uData['country']) ? $uData['country'] : "";
            $model->city = isset($uData['city']) ? $uData['city'] : "";
            $model->is_active = isset($uData['is_active']) ? $uData['is_active'] : "1";
            $model->account_type = isset($uData['account_type']) ? $uData['account_type'] : "0";
            $model->lang = isset($uData['lang']) ? $uData['lang'] : "en";

            if ($model->save()) {
                return $this->redirect(['viewown', 'id' => $model->id]);
            }
        }
        return $this->render('update', ['model' => $model,]);
    }

    public function actionUpdatepimage($id) {
        $model = $this->findModel($id);

        if ($model->id != Yii::$app->user->id) {

frontend/views/user/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use common\models\Countries;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $model backend\models\Unames */
/* @var $form yii\widgets\ActiveForm */
$colname = 'name';
$mobileMask2 = '';
$mobileMask = $mobileMask2 == "--UNKNOW--"?"":$mobileMask2;
?>
    <?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]); ?>
    <div class="row">
        <div class="col-md-6">
            <?= $form->field($model, 'f_name')->textInput(['maxlength' => true]) ?>
        </div>
        <div class="col-md-3">
            <?= $form->field($model, 'email')->textInput(['maxlength' => true]) ?>
        </div>
        <div class="col-md-3">
            <?= $form->field($model, 'phone')->textInput(['maxlength' => true]) ?>
        </div>
    </div>
    <div class="row">
        <div class="col-md-3">
            <br>
            <?= $form->field($model, 'is_active')->checkbox() ?>
        </div>
        <div class="col-md-3">
            <?php if ($mobileMask == "") { ?>
                <?= $form->field($model, 'mobile')->textInput(['maxlength' => true])?>
            <?php } else { ?>
                    <?= $form->field($model, 'mobile')->widget(yii\widgets\MaskedInput::className(), ['mask' => $mobileMask]) ?>
                <?php } ?>
            </div>

            <div class="col-md-3">
                <?= $form->field($model, 'r_currency')->dropDownList(common\config\Options::getCurrencies()); ?>
            </div>
        </div>
        <div class="row">

            <div class="col-md-6">
                <?= $form->field($model, 'address')->textInput(['maxlength' => true]) ?>
            </div>
            <div class="col-md-3">
                <?=
                $form->field($model, 'country')->dropDownList(\common\config\Options::getCountries(), ['prompt' => 'Select Country',
                    'onchange' => '
                        $.get( "' . Url::toRoute('/site/citylist') . '", { cid: $(this).val() } )
                            .done(function( data ) {
                                $( "#user-city" ).html( data );
                            }
                        );
                    '])
                ?>
            </div>
            <div class="col-md-3">
                <?php
                $cities = array();

                if ($model->country != "") {
                    $cities = \common\config\Options::getCities($model->country);
                }
                echo $form->field($model, 'city')->dropDownList($cities, ['prompt' => 'Select City']);
                ?>
            </div>

        </div>
        <div class="row">

            <div class="col-md-6">
                <?=
                $form->field($model, 'business_name')->textInput(['maxlength' => true]);
                ?>
            </div>

            <div class="col-md-3">
                <?php
                $pkgs = \common\config\Options::getLanguages();
                echo $form->field($model, 'lang')->dropDownList(ArrayHelper::map($pkgs, 'id', 'name'));
                ?>
            </div>

            <div class="col-md-3">
                <?= $form->field($model, 'avg_rate')->textInput(['maxlength' => true]);
                ?>
            </div>
        </div>
        <div class="row">

            <div class="col-md-12">
                <?=
                $form->field($model, 'notes')->textarea(['rows' => 10, 'maxlength' => true]);
                ?>
            </div>
        </div>

        <div class="form-group">
            <?= Html::submitButton($model->isNewRecord ? Yii::t('app', 'Create') : Yii::t('app', 'Update'), ['class' => $model->isNewRecord ? 'btn-u btn-u-success' : 'btn-u btn-u-success']) ?>
        </div>

        <?php ActiveForm::end(); ?>

</div>

frontend/views/user/_imgform.php
<?php

use yii\helpers\Html;
use kartik\form\ActiveForm;
use yii\helpers\ArrayHelper;
use yii\helpers\Url;
use common\models\Category;
use common\models\Subcategory;
use common\models\Businessdropdown;
use common\models\Countries;
use dosamigos\tinymce\TinyMce;

//use kartik\file\FileInput;

/* @var $this yii\web\View */
/* @var $model \common\models\Business */
/* @var $form yii\widgets\ActiveForm */
$noimage = 10;
$rmaining = $noimage - count($g_model);
?>
<?= $this->render('/site/flash'); ?>

<div class="business-form">
    <h3><?= $model->fullname ?></h3>
    <p>
        <?= Yii::t('app', 'You can upload maximum {num} images. Maximum size of image should not be more than 1MB', ['num' => $noimage]); ?>
    </p>
    <br>

    <div class ="row">
        <?php foreach ($g_model as $img) { ?>

            <div class="col-md-3" style="margin-bottom: 10px;">
                <img class="img-responsive" src="<?= Yii::$app->getUrlManager()->getBaseUrl() . '/' . $img->image_path; ?>" style="max-height:100px;" />
                <br>     
                <?=
                Html::a(Yii::t('app', 'Delete'), ['/gallery/delete', 'id' => $img->id], [
                    'class' => 'btn btn-danger',
                    'data' => [
                        'confirm' => Yii::t('app', 'Are you sure you want to delete this image?'),
                        'method' => 'post',
                    ],
                ])
                ?>
                <br> 
            </div>
        <?php } ?>
    </div>


    <?php
    $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]);
    ?>
    <?= $form->errorSummary($model); ?>
    <?= $form->field($model, 'id')->hiddenInput()->label(false) ?>
    <?= $form->field($model, 'f_name')->textInput(['readonly' => 'readonly'])->label(false) ?>


    <?php
    if ($rmaining > 0) {
        echo \kato\DropZone::widget([

            'options' => [
                'maxFilesize' => '1',
                'maxFiles' => $rmaining,
                'acceptedFiles' => "image/jpeg,image/png,image/gif",
                'url' => Url::to(['gallery/upload', 'id' => $model->id, 'type' => 13]),
                'dictDefaultMessage' => Yii::t('app', 'Drop files here to upload'),
            ],
            'clientEvents' => [
                'complete' => "function(file){console.log(file)}",
                'removedfile' => "function(file){alert(file.name + ' is removed')}"
            ],
        ]);
    }
    ?>
    <br>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Save'), ['class' => $model->isNewRecord ? 'btn-u btn-u-success chk_bus' : 'btn-u btn-u-success chk_bus        ']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/views/user/viewown.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model backend\models\Unames */

$this->title = Yii::t('app', 'User');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="row">
    <div class="col-md-12">
        <div class="row ">
            <div class="col-md-3">
                <?= $this->render('/site/left_menu'); ?>
            </div>
            <div class="col-md-9">
                <?= $this->render('/site/flash'); ?>
                <div class="headline">
                    <h2> <?= $this->title ?></h2>
                </div>
                <div class="unames-view">

                    <?php
                    $bImage = $model->b_img == "" ? "images/backbanar.jpg" : $model->b_img;
                    $cImage = $model->pic == "" ? "images/user.png" : $model->pic;
                    ?>
                    <div id='cover_container' style="background:url('<?= common\config\Options::getFrontendAddress() . $bImage; ?>');">
                        <a class="btn-u pull-right" style="margin-right: 20px;margin-top: 20px;"  href="<?= Yii::$app->urlManager->createUrl(["/user/updateimage", 'id' => $model->id]) ?>"><?= Yii::t('app', 'Update Profile Pictures') ?></a>

                        <div id='info_box'>
                            <div id="profile_img"><img src="<?= common\config\Options::getFrontendAddress() . $cImage; ?>" class='avatar_img'/></div>
                            <div id="info-box" style="<?= common\config\Options::getLangDir() == 'rtl' ? 'right: 180px;' : '' ?>">
                                <div id="info-name"><h3><?= $model->fullname ?></h3></div> 
                            </div>
                        </div>

                    </div>
                    <br>
                    <div class="row">
                        <div class="col-md-10">
                            <?php
                            if ($model->account_type == '0') {

                                echo Html::a(Yii::t('app', 'Become Service Provider'), ['/user/serviceprovider', 'id' => $model->id], [
                                    'class' => 'btn-u btn-u-blue pull-right',
                                    'data' => [
                                        'confirm' => Yii::t('app', 'Are you sure you want to become Service Provider?'),
                                    ],
                                ]);
                            }
                            ?>
                        </div>                             

                        <div class="col-md-2">

                            <a class="btn-u pull-right"  href="<?= Yii::$app->urlManager->createUrl(["/user/update", 'id' => $model->id]) ?>"><?= Yii::t('app', 'Update') ?></a>
                        </div>
                    </div>

                    <?php
                    if (common\config\Options::getIsServiceProvider())
                        echo $this->render('/site/_stars', ['score' => $model->rating, 'reviews' => $model->reveiws]);
                    ?>                    
                    <div class = "headline margin-bottom-5"><h4><?= $model->getAttributeLabel('notes') ?></h4></div>

                    <div class="row">
                        <div class="col-md-6">
                            <p><?= nl2br($model->notes) ?></p>
                        </div>
                    </div>
                    <br>
                    <div class="row">
                        <div class="col-md-6">
                            <?=
                            DetailView::widget([
                                'model' => $model,
                                'attributes' => [
                                    'username',
                                    'email',
                                    [
                                        'attribute' => 'account_type',
                                        'value' => common\config\Options::getAccountTypeById($model->account_type)
                                    ],
                                    [
                                        'attribute' => 'is_active',
                                        'value' => common\config\Options::getYesNoById($model->is_active)
                                    ],
                                    [
                                        'attribute' => 'lang',
                                        'value' => \common\models\Languages::findOne($model->lang)->name
                                    ],
                                    [
                                        'attribute' => 'showrate',
                                        'visible' => $model->account_type == '1'
                                    ],
                                ],
                            ])
                            ?>
                        </div>
                        <div class="col-md-6">
                            <?=
                            DetailView::widget([
                                'model' => $model,
                                'attributes' => [

                                    'mobile',
                                    'phone',
                                    'address',
                                    [
                                        'attribute' => 'city',
                                        'value' => $model->city == "" ? null : Yii::t('app', \common\models\Cities::findOne($model->city)->name)
                                    ],
                                    [
                                        'attribute' => 'country',
                                        'value' => $model->country == "" ? null : Yii::t('app', \common\models\Countries::findOne($model->country)->name)
                                    ],
                                    'device',
                                ],
                            ])
                            ?>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <a class="btn-u pull-right"  href="<?= Yii::$app->urlManager->createUrl(["/user/updatelocation", 'id' => $model->id]) ?>"><?= Yii::t('app', 'Update Location') ?></a>
                        </div>
                    </div>
                    <?= $this->render('/user/showmap', ['model' => $model]); ?>

                    <?= $this->render('/user/otherimages', ['id' => $model->id,'own'=>true]); ?>
                </div>
            </div>
        </div>
    </div>
</div>



<style>
    #container{
        margin:0 auto;
        width:100%;
        height: 100px;
    }

    #container-content{
        border:solid 1px #cccccc;
        padding:20px;
        width:100%;

        color:#cccccc;
    }

    #info_box{
        padding:60px 50px 0px 10px;
        border:solid 1px #dedede;
        width:538px;
        background-color:#fcfcfc;
        margin-top:88px;
    }

    #profile_img{
        background-color: #FFFFFF;
        border: 1px solid #DEDEDE;
        margin-left: 10px;
        margin-top: -100px;
        position: absolute;
        width: 86px;
        height: 86px;
        float:left;
    }

    .avatar_img{
        padding:3px;
        width: 85px;
        height: 85px;
    }

    #cover_container{
        overflow: auto;
        width: 100%;
        height:150px;

    }

    #info-box{
        margin-left:115px;
        margin-top: -50px;
        position: absolute;
    }

    #info-name{
        float:left;
        overflow:hidden;
        word-wrap: break-word;
        width:400px;
    }

    #info-content{
        margin-left:170px;
        width:290px;
    }

    #info-photos{
        text-align:center;
        font-size:11px;
        padding:5px;
        float:left;
        width:80px;
        border:solid 1px #eeeeee;
        -moz-border-radius: 3px;-webkit-border-radius: 3px;border-radius: 3px;
    }

    #info-friends{
        text-align:center;
        font-size:11px;
        padding:5px;
        margin-left:100px;
        border:solid 1px #eeeeee;
        width:80px;
        -moz-border-radius: 3px;-webkit-border-radius: 3px;border-radius: 3px;
    }
</style>